name: 'composite_action_dockertag'
description: 'macro read branchname output Dockertag and Dockertag SHA'

runs:
  using: "composite"
  steps:
    - run: |
        echo ${AVSCANWEBSERVER_REPO}
        echo ${github.ref}
        echo ${env.GITHUB_SHA}
      shell: bash
