name: 'composite_action_dockertag'
description: 'macro read branchname output Dockertag and Dockertag SHA'

runs:
  using: "composite"
  steps:
    - run: echo ${DOCKER_TAG_POSTFIX}
      shell: bash
    - name: cancel workflow if Dockertag is empty String
      uses: andymckay/cancel-action@0.2
