name: 'composite_action_dockertag'
description: 'macro read branchname output Dockertag and Dockertag SHA'
inputs:
  AVCHECK_VERSION:
    required: true
    default: ''
  GIT_SHA:
    required: true
    default: ''
  JIRA_TicketID:
    required: true
    default: ''  
  BRANCH_PREFIX:
    required: true
    default: ''
  DOCKER_TAG_POSTFIX:
    default: ''
  DOCKER_TAG_SHA:
    default: ''
outputs:
  docker-tag:
    value: ${{ steps.docker-tag.outputs.docker-tag }}
  docker-sha:
    value: ${{ steps.docker-sha.outputs.docker-sha }}

runs:
  using: "composite"
  steps:
    - name: start macro
      run:  echo start
      shell: bash
      # Assemble the Dockertag for the build image based on the type of the branch
      # Same convention as implemented OPS-1664
      # develop -> just develop_latest
    - name: Assemble Dockertag for feature
      run: |
        $DOCKER_TAG_POSTFIX="feature_${{env.JIRA_TicketID}}_latest"
        $DOCKER_TAG_SHA=""
      shell: bash
    - name: end-macro
      run: echo macro end
      shell: bash
      # Export      
    - id: docker-tag
      run: echo "::set-output name=docker-tag::$(echo $DOCKER_TAG_POSTFIX)"
      shell: bash
    - id: docker-sha
      run: echo "::set-output name=docker-sha::$(echo $DOCKER_TAG_SHA)"
      shell: bash
